### ISSUE TITLE
Respect TS_NODE_PROJECT definition

### ISSUE THREAD

**Issue by mb-dev** [jonaskello/tsconfig-paths#2]
ts-node allows defining a custom tsconfig path by defining the TS_NODE_PROJECT environment variable. Will be great to have this module also support the override.

**Comment by jonaskello** [comment]
Sure, sounds like a nice feature! I'll have a look at adding it.

**Comment by Jontem** [comment]
I've made an implementation b1f6369482950842332d02da3ba368b6886da32c that we can continue to build on. I was thinking of make it possible to override the baseUrl by also setting an enviroment variable. This could be useful when only using `tsc` and run node directly with the build output in another directory

**Comment by jonaskello** [comment]
So @Jontem and I discussed this a bit and realised that we could give the register function a parameter where you provide the `tsocnfig.json` content. Then you can wrap our register in a small js file and load the tsconfig content from anywhere you want. 

So if you wrap the tsconfigPaths.register() function within your own `bootstrap.js` file:

```
const tsconfig = require("/my/path/to/tsconfig.json");
const tsconfigPaths = require("tsconfig-paths");
tsconfigPaths.register(tsconfig)
```

You can then use it like this:

```
ts-node -r bootstrap.js main.ts
```

I think this is a good way to enable loading tsconfig from anywhere. 
But we should also support then environment variable `$TS_NODE_PROJECT` so you don't have to provide a custom js file for the simple cases. So the order for how we look for tsconfig would be:

1. Parameter passed to register() function.
2. Environment variable `$TS_NODE_PROJECT`
3. Look in the file system from current folder upwards.

**Comment by Jontem** [comment]
This is now in [2.0.0](https://github.com/jonaskello/tsconfig-paths/releases/tag/2.0.0)
