### ISSUE TITLE
tsconfig-paths doesn't load TS_NODE_PROJECT when pointing directly to a file

### ISSUE THREAD

**Issue by cvle** [jonaskello/tsconfig-paths#3]
When I set  `TS_NODE_PROJECT` directly to the config like `TS_NODE_PROJECT=custom.json` then `tsconfig-paths` complains that it cannot find the `tsconfig.json` file. This differs from the `ts-node` project that parses the file directly instead of looking for a `tsconfig.json` file.

**Comment by Jontem** [comment]
Yes that is correct. I'll fix that.

**Comment by Jontem** [comment]
This is fixed in v2.1.0
