### ISSUE TITLE
Cannot find module 'tsconfig-paths/register'

### ISSUE THREAD

**Issue by xblox** [jonaskello/tsconfig-paths#5]
hi,

I am running this via npm run script: 

scripts{ run  : nodemon -w src -x ts-node -r tsconfig-paths/register src/index.ts --user='../../user' }

gives me : 

    at Object.<anonymous> (/PMaster/projects/x4mm/server/nodejs/lib/node_modules/ts-node/src/_bin.ts:165:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)

If i run the same thing (nodemon -w src -x ts-node -r tsconfig-paths/register src/index.ts --user='../../user')
in the terminal , its all ok.
any idea ? 

thanks a lot for this extension!

**Comment by Jontem** [comment]
Hi!

It looks like you missed to post the actual error i'm only seeing a stacktrace. Can you please share it.

What i'm guessing is that this has to do with how npm scripts works because it works directly in the terminal. I've had the same problem med when using npm scripts and paths outside the "project root".

I can't see that this is a problem in tsconfig-paths

**Comment by xblox** [comment]
> xcf-server@0.0.1 dev /PMaster/projects/x4mm/server/nodejs/lib
> nodemon -w src -x ts-node -r tsconfig-paths/register src/index.ts --user='../../user'

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /PMaster/projects/x4mm/server/nodejs/lib/src/**/*
[nodemon] starting `ts-node -r tsconfig-paths/register src/index.ts --user=../../user`
Error: Cannot find module 'tsconfig-paths/register'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Object.<anonymous> (/PMaster/projects/x4mm/server/nodejs/lib/node_modules/ts-node/src/_bin.ts:165:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)

well, thanks already.

no idea who to blame either. feel free to close this, i can live with a bash shell instead, pita but ok.

**Comment by Jontem** [comment]
Sorry but i can't reproduce this. Maybe you can do a repro?

What does the ```--user=../../user``` do? Does it work without it?

**Comment by jonaskello** [comment]
I'm also using this package to run nodemon as an npm script and I have it working. Here is my npm script:

```
 "scripts": {
     "start:server": "nodemon --watch ./ --exec \"cd src/server && ts-node -r tsconfig-paths/register\" server.ts",
}
```

Looks similar to what you have but I have my exec part in quotes, not sure if that helps.

**Comment by jonaskello** [comment]
Other than that, my best guess would be that somehow your current working directory is different when you run it from npm vs from terminal. The error seems to indicate that it cannot find the module. So if it is looking from the current working dir to find  `./node_modules/ts-config-paths` and it finds it in one case but not the other it seems logical that the current working dir is different in the two cases. I'm just guessing here though.

**Comment by xblox** [comment]
@jonaskello thanks, i tried a lot but i get  "Illegal option --" for your commands. 

@Jontem --user is just an argument, same problem without. 

however, i got it working by changing to : 

`nodemon -w src -x ts-node -r ./tsconfig-paths/register src/index.ts --user='../../user'`  //mind the ./ in front of tsconfig-paths/register

thanks again!
