### ISSUE TITLE
Warning message should be displayed in case of misconfigured "tsconfig.json"

### ISSUE THREAD

**Issue by mnasyrov** [jonaskello/tsconfig-paths#6]
Currently `tsconfig-paths` fails in case `tsconfig.json` does not declared "paths" settings.
It will be better to display a meaningful warning or error message instead.

**Comment by Jontem** [comment]
I've implemented it as warning message in version 2.1.2. 

If `tsconfig.json` or `paths` in `compilerOptions` is missing it will show a warning message and will not patch `Module._load`. So it would work as `ts-node` without `tsconfig-paths`.

But if `baseUrl` is missing from `compilerOptions` we will also show a warning message but typescript itself will throw an exception about missing the `baseUrl`property.
